# Generated by Django 3.0.3 on 2020-07-30 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movies',
        ),
        migrations.RenameModel(
            old_name='Rating',
            new_name='Ratings',
        ),
    ]
