# Generated by Django 3.0.3 on 2020-07-30 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielens', '0002_auto_20200730_0932'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='movies',
        ),
        migrations.AlterModelTable(
            name='ratings',
            table='ratings',
        ),
    ]
